//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auto_category> auto_category { get; set; }
        public virtual DbSet<auto_make> auto_make { get; set; }
        public virtual DbSet<auto_model> auto_model { get; set; }
        public virtual DbSet<auto_package> auto_package { get; set; }
        public virtual DbSet<auto_package_custom_part_xref> auto_package_custom_part_xref { get; set; }
        public virtual DbSet<auto_package_jobber_part_xref> auto_package_jobber_part_xref { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<client_auto_make_xref> client_auto_make_xref { get; set; }
        public virtual DbSet<client_jobber_company_xref> client_jobber_company_xref { get; set; }
        public virtual DbSet<client_jobber_company_xref_jobber_part_xref> client_jobber_company_xref_jobber_part_xref { get; set; }
        public virtual DbSet<client_rates> client_rates { get; set; }
        public virtual DbSet<custom_category> custom_category { get; set; }
        public virtual DbSet<custom_company> custom_company { get; set; }
        public virtual DbSet<custom_image> custom_image { get; set; }
        public virtual DbSet<custom_index> custom_index { get; set; }
        public virtual DbSet<custom_part> custom_part { get; set; }
        public virtual DbSet<custom_subcategory> custom_subcategory { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<jobber_catalog> jobber_catalog { get; set; }
        public virtual DbSet<jobber_category> jobber_category { get; set; }
        public virtual DbSet<jobber_company> jobber_company { get; set; }
        public virtual DbSet<jobber_index> jobber_index { get; set; }
        public virtual DbSet<jobber_part> jobber_part { get; set; }
        public virtual DbSet<jobber_subcategory> jobber_subcategory { get; set; }
        public virtual DbSet<province> provinces { get; set; }
        public virtual DbSet<quote> quotes { get; set; }
        public virtual DbSet<quote_custom_part> quote_custom_part { get; set; }
        public virtual DbSet<quote_jobber_part_xref> quote_jobber_part_xref { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<users_client_xref> users_client_xref { get; set; }
        public virtual DbSet<users_jobber_company_xref> users_jobber_company_xref { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<year> years { get; set; }
        public virtual DbSet<vw_part_extended> vw_part_extended { get; set; }
        public virtual DbSet<vw_part_extended_no_auto> vw_part_extended_no_auto { get; set; }
    
        public virtual int up_auto_package_custom_part_xref_add_by_list(Nullable<int> custom_part_id, string list_auto_package_id)
        {
            var custom_part_idParameter = custom_part_id.HasValue ?
                new ObjectParameter("custom_part_id", custom_part_id) :
                new ObjectParameter("custom_part_id", typeof(int));
    
            var list_auto_package_idParameter = list_auto_package_id != null ?
                new ObjectParameter("list_auto_package_id", list_auto_package_id) :
                new ObjectParameter("list_auto_package_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_auto_package_custom_part_xref_add_by_list", custom_part_idParameter, list_auto_package_idParameter);
        }
    
        public virtual int up_auto_package_custom_part_xref_add_to_all(Nullable<int> custom_part_id)
        {
            var custom_part_idParameter = custom_part_id.HasValue ?
                new ObjectParameter("custom_part_id", custom_part_id) :
                new ObjectParameter("custom_part_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_auto_package_custom_part_xref_add_to_all", custom_part_idParameter);
        }
    
        public virtual int up_client_jobber_company_xref_delByclient_id(Nullable<int> client_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_client_jobber_company_xref_delByclient_id", client_idParameter);
        }
    
        public virtual int up_client_jobber_company_xref_jobber_part_xref_add_all(Nullable<int> client_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_client_jobber_company_xref_jobber_part_xref_add_all", client_idParameter);
        }
    
        public virtual int up_client_jobber_company_xref_jobber_part_xref_delByclient_jobber_company_xref_id(Nullable<int> client_jobber_company_xref_id)
        {
            var client_jobber_company_xref_idParameter = client_jobber_company_xref_id.HasValue ?
                new ObjectParameter("client_jobber_company_xref_id", client_jobber_company_xref_id) :
                new ObjectParameter("client_jobber_company_xref_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_client_jobber_company_xref_jobber_part_xref_delByclient_jobber_company_xref_id", client_jobber_company_xref_idParameter);
        }
    
        public virtual int up_client_jobber_company_xref_jobber_part_xref_upd_with_price(Nullable<int> client_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_client_jobber_company_xref_jobber_part_xref_upd_with_price", client_idParameter);
        }
    
        public virtual int up_client_jobber_company_xref_jobber_part_xref_upd_with_priceByCompanyID(Nullable<int> client_id, Nullable<int> company_id)
        {
            var client_idParameter = client_id.HasValue ?
                new ObjectParameter("client_id", client_id) :
                new ObjectParameter("client_id", typeof(int));
    
            var company_idParameter = company_id.HasValue ?
                new ObjectParameter("company_id", company_id) :
                new ObjectParameter("company_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("up_client_jobber_company_xref_jobber_part_xref_upd_with_priceByCompanyID", client_idParameter, company_idParameter);
        }
    
        public virtual ObjectResult<up_quote_sel_Result> up_quote_sel(Nullable<int> quote_id)
        {
            var quote_idParameter = quote_id.HasValue ?
                new ObjectParameter("quote_id", quote_id) :
                new ObjectParameter("quote_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<up_quote_sel_Result>("up_quote_sel", quote_idParameter);
        }
    }
}
