//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto_model
    {
        public auto_model()
        {
            this.auto_package = new HashSet<auto_package>();
        }
    
        public int auto_model_id { get; set; }
        public int year_id { get; set; }
        public int auto_make_id { get; set; }
        public int auto_category_id { get; set; }
        public string auto_model_desc { get; set; }
        public int auto_model_code { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual auto_category auto_category { get; set; }
        public virtual auto_make auto_make { get; set; }
        public virtual year year { get; set; }
        public virtual ICollection<auto_package> auto_package { get; set; }
    }
}
