//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auto_make
    {
        public auto_make()
        {
            this.auto_model = new HashSet<auto_model>();
            this.client_auto_make_xref = new HashSet<client_auto_make_xref>();
        }
    
        public int auto_make_id { get; set; }
        public string auto_make_desc { get; set; }
        public int auto_make_code { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual ICollection<auto_model> auto_model { get; set; }
        public virtual ICollection<client_auto_make_xref> client_auto_make_xref { get; set; }
    }
}
