//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.client_auto_make_xref = new HashSet<client_auto_make_xref>();
            this.client_jobber_company_xref = new HashSet<client_jobber_company_xref>();
            this.client_rates = new HashSet<client_rates>();
            this.custom_category = new HashSet<custom_category>();
            this.custom_company = new HashSet<custom_company>();
            this.custom_index = new HashSet<custom_index>();
            this.custom_part = new HashSet<custom_part>();
            this.custom_subcategory = new HashSet<custom_subcategory>();
            this.quotes = new HashSet<quote>();
            this.users_client_xref = new HashSet<users_client_xref>();
        }
    
        public int client_id { get; set; }
        public string account_number { get; set; }
        public string dealership_name { get; set; }
        public string contact_name { get; set; }
        public string email_address { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> province_id { get; set; }
        public string postal_code { get; set; }
        public string fax { get; set; }
        public string phone { get; set; }
        public string icon { get; set; }
        public string web_address { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual ICollection<client_auto_make_xref> client_auto_make_xref { get; set; }
        public virtual ICollection<client_jobber_company_xref> client_jobber_company_xref { get; set; }
        public virtual province province { get; set; }
        public virtual ICollection<client_rates> client_rates { get; set; }
        public virtual ICollection<custom_category> custom_category { get; set; }
        public virtual ICollection<custom_company> custom_company { get; set; }
        public virtual ICollection<custom_index> custom_index { get; set; }
        public virtual ICollection<custom_part> custom_part { get; set; }
        public virtual ICollection<custom_subcategory> custom_subcategory { get; set; }
        public virtual ICollection<quote> quotes { get; set; }
        public virtual ICollection<users_client_xref> users_client_xref { get; set; }
    }
}
