//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_rates
    {
        public int client_rates_id { get; set; }
        public int client_id { get; set; }
        public decimal mechanical_rate { get; set; }
        public decimal body_rate { get; set; }
        public decimal paint_rate { get; set; }
        public decimal mechanical_shop_supplies { get; set; }
        public decimal body_shop_supplies { get; set; }
        public decimal paint_shop_supplies { get; set; }
        public bool retail_or_cost { get; set; }
        public Nullable<decimal> rate_adjustment { get; set; }
        public bool rate_adjustment_plus_or_minus { get; set; }
        public decimal GST { get; set; }
        public decimal PST { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual client client { get; set; }
    }
}
