//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_jobber_company_xref_jobber_part_xref
    {
        public int client_jobber_company_xref_jobber_part_xref_id { get; set; }
        public int client_jobber_company_xref_id { get; set; }
        public int jobber_part_id { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<decimal> retail_price { get; set; }
        public Nullable<decimal> mechanical_hours { get; set; }
        public Nullable<decimal> body_hours { get; set; }
        public Nullable<decimal> paint_hours { get; set; }
        public Nullable<decimal> mechanical_shop_supplies { get; set; }
        public Nullable<decimal> body_shop_supplies { get; set; }
        public Nullable<decimal> paint_shop_supplies { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual client_jobber_company_xref client_jobber_company_xref { get; set; }
        public virtual jobber_part jobber_part { get; set; }
    }
}
