//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_image
    {
        public custom_image()
        {
            this.custom_part = new HashSet<custom_part>();
        }
    
        public int custom_image_id { get; set; }
        public string custom_image_name { get; set; }
        public int custom_image_code { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual ICollection<custom_part> custom_part { get; set; }
    }
}
