//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom_category
    {
        public custom_category()
        {
            this.custom_subcategory = new HashSet<custom_subcategory>();
        }
    
        public int custom_category_id { get; set; }
        public string custom_category_desc { get; set; }
        public int custom_category_code { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public int client_id { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual client client { get; set; }
        public virtual ICollection<custom_subcategory> custom_subcategory { get; set; }
    }
}
