//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobber_subcategory
    {
        public jobber_subcategory()
        {
            this.jobber_part = new HashSet<jobber_part>();
        }
    
        public int jobber_subcategory_id { get; set; }
        public int jobber_category_id { get; set; }
        public int jobber_company_id { get; set; }
        public string jobber_subcategory_short_desc { get; set; }
        public string jobber_subcategory_long_desc { get; set; }
        public int jobber_subcategory_code { get; set; }
        public int jobber_index_id { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual jobber_category jobber_category { get; set; }
        public virtual jobber_company jobber_company { get; set; }
        public virtual jobber_index jobber_index { get; set; }
        public virtual ICollection<jobber_part> jobber_part { get; set; }
    }
}
