//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobber_company
    {
        public jobber_company()
        {
            this.client_jobber_company_xref = new HashSet<client_jobber_company_xref>();
            this.jobber_subcategory = new HashSet<jobber_subcategory>();
            this.users_jobber_company_xref = new HashSet<users_jobber_company_xref>();
        }
    
        public int jobber_company_id { get; set; }
        public string jobber_company_name { get; set; }
        public int jobber_company_code { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual ICollection<client_jobber_company_xref> client_jobber_company_xref { get; set; }
        public virtual ICollection<jobber_subcategory> jobber_subcategory { get; set; }
        public virtual ICollection<users_jobber_company_xref> users_jobber_company_xref { get; set; }
    }
}
