//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobber_category
    {
        public jobber_category()
        {
            this.jobber_subcategory = new HashSet<jobber_subcategory>();
        }
    
        public int jobber_category_id { get; set; }
        public string jobber_category_desc { get; set; }
        public int jobber_category_code { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual ICollection<jobber_subcategory> jobber_subcategory { get; set; }
    }
}
