//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobber_part
    {
        public jobber_part()
        {
            this.auto_package_jobber_part_xref = new HashSet<auto_package_jobber_part_xref>();
            this.client_jobber_company_xref_jobber_part_xref = new HashSet<client_jobber_company_xref_jobber_part_xref>();
            this.quote_jobber_part_xref = new HashSet<quote_jobber_part_xref>();
        }
    
        public int jobber_part_id { get; set; }
        public int jobber_subcategory_id { get; set; }
        public string jobber_part_desc { get; set; }
        public string jobber_part_no { get; set; }
        public System.DateTime eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public int jobber_catalog_id { get; set; }
        public int image_id { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
        public Nullable<decimal> suggested_retail_price { get; set; }
    
        public virtual ICollection<auto_package_jobber_part_xref> auto_package_jobber_part_xref { get; set; }
        public virtual ICollection<client_jobber_company_xref_jobber_part_xref> client_jobber_company_xref_jobber_part_xref { get; set; }
        public virtual image image { get; set; }
        public virtual jobber_catalog jobber_catalog { get; set; }
        public virtual jobber_subcategory jobber_subcategory { get; set; }
        public virtual ICollection<quote_jobber_part_xref> quote_jobber_part_xref { get; set; }
    }
}
