//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote_jobber_part_xref
    {
        public int quote_jobber_part_xref_id { get; set; }
        public int quote_id { get; set; }
        public Nullable<int> jobber_part_id { get; set; }
        public decimal retail_price { get; set; }
        public decimal mechanical_hours { get; set; }
        public decimal body_hours { get; set; }
        public decimal paint_hours { get; set; }
        public decimal mechanical_rate { get; set; }
        public decimal body_rate { get; set; }
        public decimal paint_rate { get; set; }
        public decimal mechanical_shop_supplies { get; set; }
        public decimal body_shop_supplies { get; set; }
        public decimal paint_shop_supplies { get; set; }
        public decimal install_price { get; set; }
        public decimal shop_supplies { get; set; }
        public decimal total_price { get; set; }
        public int quantity { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
        public Nullable<int> custom_part_id { get; set; }
    
        public virtual custom_part custom_part { get; set; }
        public virtual jobber_part jobber_part { get; set; }
        public virtual quote quote { get; set; }
    }
}
