//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote
    {
        public quote()
        {
            this.quote_custom_part = new HashSet<quote_custom_part>();
            this.quote_jobber_part_xref = new HashSet<quote_jobber_part_xref>();
        }
    
        public int quote_id { get; set; }
        public int client_id { get; set; }
        public string quote_no { get; set; }
        public int auto_package_id { get; set; }
        public int UserId { get; set; }
        public string salesman { get; set; }
        public string customer { get; set; }
        public string email_address { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public Nullable<int> province_id { get; set; }
        public string postal_code { get; set; }
        public string phone { get; set; }
        public string comments { get; set; }
        public string vehicle_stock { get; set; }
        public string vehicle_vin { get; set; }
        public bool sold { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
        public Nullable<decimal> discount { get; set; }
    
        public virtual auto_package auto_package { get; set; }
        public virtual client client { get; set; }
        public virtual ICollection<quote_custom_part> quote_custom_part { get; set; }
        public virtual ICollection<quote_jobber_part_xref> quote_jobber_part_xref { get; set; }
    }
}
