//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote_custom_part
    {
        public int quote_custom_part_id { get; set; }
        public int quote_id { get; set; }
        public string custom_part_no { get; set; }
        public string custom_part_desc { get; set; }
        public decimal custom_part_retail_price { get; set; }
        public int custom_part_quantity { get; set; }
        public decimal custom_part_mechanical_hours { get; set; }
        public decimal custom_part_body_hours { get; set; }
        public decimal custom_part_paint_hours { get; set; }
        public decimal custom_part_mechanical_rate { get; set; }
        public decimal custom_part_body_rate { get; set; }
        public decimal custom_part_paint_rate { get; set; }
        public decimal custom_part_mechanical_shop_supplies { get; set; }
        public decimal custom_part_body_shop_supplies { get; set; }
        public decimal custom_part_paint_shop_supplies { get; set; }
        public decimal custom_part_install_price { get; set; }
        public decimal custom_part_shop_supplies { get; set; }
        public decimal custom_part_total_price { get; set; }
        public string row_eff_user_id { get; set; }
        public System.DateTime row_eff_date { get; set; }
    
        public virtual quote quote { get; set; }
    }
}
