//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOD_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.users_client_xref = new HashSet<users_client_xref>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
    
        public virtual ICollection<users_client_xref> users_client_xref { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
